---
apiVersion: v1
kind: Service
metadata:
    name: kubernetesapp
    labels:
        app: kubernetesapp
spec:
    type: NodePort
    selector:
        app: kubernetesapp
    ports:
        - protocol: TCP
          port: 8099
          name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kubernetesapp
spec:
    selector:
        matchLabels:
            app: kubernetesapp
    replicas: 1
    template:
        metadata:
            labels:
                app: kubernetesapp
        spec:
            containers:
                - name: kubernetesapp
                  image: medboutaieb/kubernetes_tp:latest
                  ports:
                      - containerPort: 8020
                  livenessProbe:
                      httpGet:
                          path: /healthcheck
                          port: 8025
                      initialDelaySeconds: 30
                      timeoutSeconds: 1
